package com.myspace.test;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "Demo")  

public class objet extends org.drools.persistence.jpa.marshaller.VariableEntity implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "OBJET_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "OBJET_ID_GENERATOR", sequenceName = "OBJET_ID_SEQ")
	private java.lang.Long id;

	private int entier;

	private java.lang.Integer entierobjet;

	public objet() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public int getEntier() {
		return this.entier;
	}

	public void setEntier(int entier) {
		this.entier = entier;
	}

	public java.lang.Integer getEntierobjet() {
		return this.entierobjet;
	}

	public void setEntierobjet(java.lang.Integer entierobjet) {
		this.entierobjet = entierobjet;
	}

	public objet(java.lang.Long id, int entier, java.lang.Integer entierobjet) {
		this.id = id;
		this.entier = entier;
		this.entierobjet = entierobjet;
	}

}